---
compose_vmware_tag_ansible_groups_jira:
  jira:
    version: 8.8.0
    domain: jira.balmerfamilyfarm.com
    http_port: 8080
    mounts:
      app:
        local: /mnt/jira
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/jira"
      db:
        local: /mnt/jira_db
        remote: "{{ nfs_server }}:/mnt/POOL_A/docker/jira_db"
    images:
      app: "{{ docker_registry }}/atlassian/jira-software:8.8.0"
      db: "{{ docker_registry }}/postgres:11.10"
    user: 1012
    group: 1014
    postgres_version: "11.10"
    db_user: "{{ lookup('onepassword', 'Jira Server', section='db', field='username', vault='homelab', domain=op_domain, secret_key=op_key, master_password=op_password) }}"
    db_pass: "{{ lookup('onepassword', 'Jira Server', section='db', field='password', vault='homelab', domain=op_domain, secret_key=op_key, master_password=op_password) }}"
    db_name: jira