- name: Setup Docker Composes
  hosts: docker_hosts
  gather_facts: true
  become: true
  pre_tasks:
    - name: Combine composes
      set_fact:
        composes: "{{ composes|default({}) | combine(hostvars[inventory_hostname]['compose_' + item]|default({})) }}"
      loop: "{{ group_names }}"
  roles:
    - chrisbalmer.yum-repos
    - chrisbalmer.firewall
    - chrisbalmer.nfs
    - chrisbalmer.simple-docker
    - chrisbalmer.docker-compose
